name: Publish Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Docker image to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: matthieugouel/ostatic
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
